#!/usr/bin/env python3
"""Auto-generate data/data_card.md from data/processed/{train,val,test}.jsonl.

Follows Gebru et al. 2018 'Datasheets for Datasets' conventions: motivation,
composition, splits, field-presence stats, distribution of categorical
metadata. Designed to be regenerated whenever processed/* changes.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


def _read_split(processed_dir: Path, split: str) -> list[dict]:
    p = processed_dir / f"{split}.jsonl"
    if not p.is_file():
        return []
    return [json.loads(line) for line in p.read_text().splitlines() if line.strip()]


def _field_presence(records: list[dict]) -> Counter:
    c: Counter = Counter()
    for r in records:
        for f in (r.get("fields") or {}):
            if (r["fields"][f] or {}).get("text"):
                c[f] += 1
    return c


def _categorical_dist(records: list[dict], key: str) -> Counter:
    return Counter(r.get(key) for r in records)


def build_data_card(
    processed_dir: Path | str,
    out_path: Path | str,
) -> None:
    processed_dir = Path(processed_dir)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    train = _read_split(processed_dir, "train")
    val = _read_split(processed_dir, "val")
    test = _read_split(processed_dir, "test")
    all_recs = train + val + test

    # --- Header
    lines: list[str] = [
        "# Data Card",
        "",
        "Auto-generated by `scripts/build_data_card.py`. Re-run after every "
        "data refresh.",
        "",
        "Following Gebru et al. 2018, *Datasheets for Datasets* "
        "(`papers/gebru_2018_datasheets.pdf`).",
        "",
    ]

    # --- Motivation
    lines += [
        "## Motivation",
        "",
        "This dataset supports training and evaluating a vision-language model "
        "for structured information extraction from pharmaceutical product "
        "label images. See the design spec, `docs/superpowers/specs/`, for the "
        "research goal.",
        "",
    ]

    # --- Composition
    lines += [
        "## Composition",
        "",
        f"- **Total labeled records:** {len(all_recs)}",
        "- **Image format:** JPEG, RGB, varying resolutions (resized at "
        "training time to 224×224 with letterbox padding).",
        "- **Fields per record:** variable; up to 12 OCR fields.",
        "",
    ]

    # --- Splits
    lines += [
        "## Splits",
        "",
        "| Split | Records | Notes |",
        "|---|---|---|",
        f"| train | {len(train)} | Used for parameter updates. |",
        f"| val   | {len(val)} | Used by the autoresearch loop's macro_f1 metric. |",
        f"| test  | {len(test)} | **Frozen.** Only `evaluate_test()` may read these. |",
        "",
    ]

    # --- Field presence
    lines += [
        "## Field presence",
        "",
        "Per-field presence counts in train (the agent never sees val/test field stats).",
        "",
        "| Field | Count | % |",
        "|---|---|---|",
    ]
    fp = _field_presence(train)
    for f, count in sorted(fp.items(), key=lambda kv: -kv[1]):
        pct = 100.0 * count / max(len(train), 1)
        lines.append(f"| {f} | {count} | {pct:.1f}% |")
    lines.append("")

    # --- view_type / pack_type / medicine_name
    for key in ("view_type", "pack_type", "medicine_name"):
        lines += [f"## Distribution: `{key}` (train)", ""]
        dist = _categorical_dist(train, key)
        if not dist:
            lines += ["(no values)", ""]
            continue
        if len(dist) > 20:
            lines += [f"(showing top 20 of {len(dist)} unique values)", ""]
        lines += ["| Value | Count |", "|---|---|"]
        for v, c in dist.most_common(20):
            lines.append(f"| `{v!r}` | {c} |")
        lines.append("")

    # --- Maintenance
    lines += [
        "## Maintenance",
        "",
        "- Source of truth: `gs://auto_learn_meds/raw/golden_set/` "
        "(`gold_standard.jsonl` + `splits.json`).",
        "- Regenerate this file: "
        "`uv run python scripts/build_data_card.py "
        "--processed-dir data/processed --out data/data_card.md`",
        "",
    ]

    out_path.write_text("\n".join(lines))
    print(f"[build_data_card] wrote {out_path} ({len(lines)} lines)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--processed-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    build_data_card(processed_dir=args.processed_dir, out_path=args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
