#!/usr/bin/env python3
"""Regenerate experiments/leaderboard.md from experiments/ledger.jsonl.

Output is a Markdown table sorted by final_macro_f1 descending. Handy at the
top of any explore-loop session for the agent to see where the floor is.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _read_ledger(workspace: Path) -> list[dict]:
    p = workspace / "experiments" / "ledger.jsonl"
    if not p.is_file():
        return []
    out = []
    for line in p.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def regenerate(workspace: Path | str, out_path: Path | str | None = None) -> Path:
    workspace = Path(workspace)
    out_path = Path(out_path) if out_path else workspace / "experiments" / "leaderboard.md"
    entries = _read_ledger(workspace)

    lines: list[str] = []
    lines.append("# Experiments Leaderboard")
    lines.append("")
    lines.append("Auto-generated by `scripts/leaderboard.py`. Re-runs after every "
                 "`finalize_experiment.sh`.")
    lines.append("")

    if not entries:
        lines.append("_no experiments yet_")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text("\n".join(lines) + "\n")
        return out_path

    entries_sorted = sorted(
        entries,
        key=lambda e: (e.get("metrics") or {}).get("final_macro_f1", -1.0),
        reverse=True,
    )

    kept_count = sum(1 for e in entries if e.get("kept"))
    lines.append(f"**{len(entries)} experiments total · {kept_count} kept · "
                 f"current floor: {entries_sorted[0]['metrics']['final_macro_f1']:.4f}**")
    lines.append("")

    lines.append("| rank | run_id | phase | macro_f1 | kept | wall (min) | hypothesis |")
    lines.append("|---|---|---|---|---|---|---|")
    for rank, e in enumerate(entries_sorted, start=1):
        f1 = (e.get("metrics") or {}).get("final_macro_f1", -1.0)
        kept = "✓" if e.get("kept") else "✗"
        wall = e.get("wall_clock_min", "?")
        hyp_lines = (e.get("hypothesis") or "").splitlines()
        hyp = (hyp_lines[0] if hyp_lines else "")[:60]
        lines.append(
            f"| {rank} | {e.get('run_id', '?')} | {e.get('phase', '?')} | "
            f"{f1:.4f} | {kept} | {wall} | {hyp} |"
        )
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--workspace", type=Path, default=Path("/workspace"))
    parser.add_argument("--out", type=Path, default=None,
                        help="Output path; defaults to <workspace>/experiments/leaderboard.md")
    args = parser.parse_args()
    out = regenerate(args.workspace, args.out)
    print(f"[leaderboard] wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
